export const BASE_URL= process.env.BASE_URL || "http://144.24.105.148:8081"
export const USERNAME= process.env.USERNAME || "krushna"
export const PASSWORD= process.env.PASSWORD || "krushna"
export const TODO_RESOURCE= "/v3/todo"
export const USER_RESOURCE= "/v3/user"
export const USER_LOGIN_RESOURCE= "/v3/user/login"
export const NEWUSERNAME= process.env.NEWUSERNAME || "krushna123"
export const NEWPASSWORD= process.env.NEWPASSWORD || "krushna123"